# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default=b'localhost', max_length=255)),
                ('keepalive', models.IntegerField(default=60)),
                ('title', models.CharField(blank=True, default=b'BMKG MQTT', max_length=255)),
                ('refresh', models.IntegerField(default=300)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopicSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('subscribe', models.BooleanField(default=False)),
            ],
        ),
    ]
