# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsetting',
            name='table',
            field=models.CharField(blank=True, choices=[(b'digital_forecast', b'Digital Forecast'), (b'maritim_cuaca_pelayanan', b'Maritim Cuaca Pelayanan'), (b'maritim_cuaca_pelabuhan', b'Maritim Cuaca Pelabuhan'), (b'maritim_cuaca_penyebrangan', b'Maritim Cuaca Penyebrangan'), (b'maritim_wisata_bahari', b'Maritim Wisata Bahari'), (b'satelit_hotspot_modis', b'Satelit Hotspot Modis'), (b'satelit_himawari_8_natural_color', b'Satelit Himawari 8 Naturan Color'), (b'satelit_himawari_8_ir_enhanced', b'Satelit Himawari 8 IR Enhanced'), (b'gempa_terkini', b'Gempa Terkini'), (b'gempa_terkini_csv', b'Gempa Terkini CSV'), (b'gempa_dirasakan', b'Gempa Dirasakan'), (b'iklim_kabupaten_csv', b'Iklim Kabupaten CSV'), (b'iklim_kecamatan_csv', b'Iklim Kecamatan CSV'), (b'iklim_desa_csv', b'Iklim Desa CSV')], max_length=255),
        ),
    ]
