# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180219_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='address',
            field=models.CharField(default=b'localhost', max_length=255, verbose_name=b'Broker Address'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='client_id',
            field=models.CharField(max_length=255, verbose_name=b'Broker Client ID'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='client_id_sub',
            field=models.CharField(max_length=255, verbose_name=b'Broker Client ID Sub'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='keepalive',
            field=models.IntegerField(default=60, verbose_name=b'Broker Keepalive'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='password',
            field=models.CharField(max_length=255, verbose_name=b'Broker Password'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='refresh',
            field=models.IntegerField(default=300, verbose_name=b'Refresh (s)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='title',
            field=models.CharField(default=b'BMKG MQTT', max_length=255, verbose_name=b'Site Title'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='user',
            field=models.CharField(max_length=255, verbose_name=b'Broker User'),
        ),
    ]
