# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180219_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='show_area_id',
            field=models.IntegerField(blank=True, default=300, verbose_name=b'Filter Area ID'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='show_bps_id_des',
            field=models.IntegerField(blank=True, default=300, verbose_name=b'Filter BPS ID (Desa)'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='show_bps_id_kab',
            field=models.IntegerField(blank=True, default=300, verbose_name=b'Filter BPS ID (Kabupaten)'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='show_bps_id_kec',
            field=models.IntegerField(blank=True, default=300, verbose_name=b'Filter BPS ID (Kecamatan)'),
        ),
    ]
