# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180221_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='show_area_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Filter Area ID'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='show_bps_id_des',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Filter BPS ID (Desa)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='show_bps_id_kab',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Filter BPS ID (Kabupaten)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='show_bps_id_kec',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Filter BPS ID (Kecamatan)'),
        ),
    ]
